/****************************************************************
ARMA Mission Development Framework
ADF version: 1.43 / JANUARY 2016

Script: Mission initialization countdown timer
Author: Whiztler
Script version: 1.49

Game type: n/a
File: ADF_init_post.sqf
****************************************************************
DO NOT EDIT THIS FILE

Configure the mission timer in ADF_init_config.sqf
****************************************************************/

diag_log "ADF RPT: Init - executing ADF_init_post.sqf"; // Reporting. Do NOT edit/remove

if (ADF_debug) then {
	{
		private "_m";
		_m = "DIAG - Script executed: " + str _x;
		[_m, false] call ADF_fnc_log;
	} forEach diag_activeSQFScripts;
};

// Init
params ["_t", "_vt", "_vm", "_db", "_dn"];
private ["_u", "_c", "_ms"];

_u 	= player;
_vt 	= str _vt;
_vm 	= str _vm;
_t 	= _t / 100;
_ms 	= "[ADF] ARMA Mission Development Framework v";
_c	= 0;

if (isServer) then {
	private ["_vb"];
	If ((_db == "Alpha") || (_db == "Beta")) then {
		_vb =  format [" (Build: %1 %2)", _db, _dn];
		_ms = _ms + _vt + _vb;	
	} else {
		_ms = _ms + _vt;
	};

	_m = createMarker ["mADF_version",[5,-200, 0]];
	_m setMarkerSize [0, 0];
	_m setMarkerShape "ICON";
	_m setMarkerType "mil_box";
	_m setMarkerColor "ColorGrey";
	_m setMarkerDir 0;
	_m setMarkerText _ms;
	
	if ({side _x == east} count allUnits == 0) then {createCenter east};
	if ({side _x == west} count allUnits == 0) then {createCenter west};
	if ({side _x == resistance} count allUnits == 0) then {createCenter resistance};
	if ({side _x == civilian} count allUnits == 0) then {createCenter civilian};
};

If (isDedicated || ADF_isHC) exitWith {ADF_missionInit = true;};
if (time > 300) exitWith {ADF_missionInit = true;};
if (ADF_debug) exitWith {ADF_missionInit = true; publicVariable "ADF_missionInit"; ["INIT - debug mode detected, skipping mission init timer", false] call ADF_fnc_log;};
if (isMultiplayer) then {_u enableSimulation false; showMap false;};

If ((_db == "Alpha") || (_db == "Beta")) then {
	private "_msg";
	_msg = format ["This is a development build of ADF (%1 - %2 %3). Do not use for live missions!", _vt, _db, _dn];
	_msg remoteExec ["systemChat", -2, false];  // v.1.42 B01	
};
		
while {(_c != 100)} do {
	private "_msg";
	_c = _c + 1;
	
	_msg = format ["
		<br/>
		<t align='left' size='1.1' color='#A1A4AD'>Mission Initializing: </t>
		<t size='1.1' align='left' color='#F7D358' font='PuristaBold'>%1&#0037;</t><t size='1.1' align='left' color='#A1A4AD'> done</t><br/><br/>
		<t align='left' color='#A1A4AD'>- Refrain from moving!</t><br/>
		<t align='left' color='#A1A4AD'>- Do not use your radio!</t><br/>
		<t align='left' color='#A1A4AD'>- Follow TL orders</t><br/>
		<t align='left' color='#A1A4AD'>- Init takes approx %2 secs</t><br/><br/>
		<t align='left' color='#A1A4AD'>Tpl: <t color='#FFFFFF' align='left'>%3</t>  |  Mission: </t><t color='#FFFFFF' align='left'>%4</t><br/>
	", _c, _t * 100, _vt, _vm];

	If ((_db == "Alpha") || (_db == "Beta")) then {
		_msg = _msg + format ["
			<t align='left' color='#A1A4AD'>Build: <t color='#FFFFFF' align='left'>%1</t>  |  Build version: </t><t color='#FFFFFF' align='left'>%2</t><br/>
		", _db, _dn];
	};	
	sleep _t;
	hintSilent parseText _msg; 
};

if (isMultiplayer) then {_u enableSimulation true; showMap true;};

private "_msg";
_msg = format ["
	<br/>
	<t size='1.1' color='#FFFFFF' align='left'>Mission initializing complete</t>
	<t size='1' align='left' color='#A1A4AD'><br/><br/>
	- Refrain from moving!<br/>
	- Do not use your radio!<br/>
	- Follow TL orders<br/>
	- Init takes approx %1 secs<br/><br/>
	Tpl: %2  |  Mission: %3</t><br/><br/>
", _t * 100, _vt, _vm];

If ((_db == "Alpha") || (_db == "Beta")) then {
	_msg = _msg + format ["
		<t align='left' color='#A1A4AD'>Build: %1 | Build version: %2</t><br/>
	", _db, _dn];
};

hintSilent parseText _msg;
finishMissionInit;
sleep 3; hintSilent "";
ADF_missionInit = true; 
if (ADF_debug) then {["INIT - MissionInit Timer done", false] call ADF_fnc_log};

